services:
  mongo:
    container_name: ${CONTAINER_NAME}
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - to-be-restored:/to-be-restored

volumes:
  to-be-restored:
    external: false
  mongo-data:
    external: false

